import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib"

import type { ImprovedResumeContent } from "@/schemas/jdAnalysisSchema"

type ImprovedCvMeta = {
  jobTitle?: string
  companyName?: string
  fileName?: string
  generatedAt?: string
}

const PAGE_WIDTH = 595.28
const PAGE_HEIGHT = 841.89
const MARGIN_X = 48
const TOP_MARGIN = 56
const BOTTOM_MARGIN = 50
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const words = text.trim().split(/\s+/).filter(Boolean)
  if (words.length === 0) return [""]

  const lines: string[] = []
  let current = ""

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate
      continue
    }
    if (current) {
      lines.push(current)
      current = word
      continue
    }
    let chunk = ""
    for (const ch of word) {
      const next = `${chunk}${ch}`
      if (font.widthOfTextAtSize(next, size) <= maxWidth) {
        chunk = next
      } else {
        if (chunk) lines.push(chunk)
        chunk = ch
      }
    }
    current = chunk
  }

  if (current) lines.push(current)
  return lines
}

function ensurePage(
  pdfDoc: PDFDocument,
  page: PDFPage,
  cursorY: number,
  requiredHeight: number
): { page: PDFPage; cursorY: number } {
  if (cursorY - requiredHeight >= BOTTOM_MARGIN) {
    return { page, cursorY }
  }
  const nextPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  return { page: nextPage, cursorY: PAGE_HEIGHT - TOP_MARGIN }
}

function drawBlock(params: {
  pdfDoc: PDFDocument
  page: PDFPage
  cursorY: number
  text: string
  font: PDFFont
  size: number
  color: ReturnType<typeof rgb>
  lineHeight: number
}): { page: PDFPage; cursorY: number } {
  const lines = wrapText(params.text, params.font, params.size, CONTENT_WIDTH)
  let page = params.page
  let cursorY = params.cursorY

  for (const line of lines) {
    const ensured = ensurePage(params.pdfDoc, page, cursorY, params.lineHeight)
    page = ensured.page
    cursorY = ensured.cursorY
    page.drawText(line, { x: MARGIN_X, y: cursorY, size: params.size, font: params.font, color: params.color })
    cursorY -= params.lineHeight
  }

  return { page, cursorY }
}

export async function buildImprovedCvPdf(
  content: ImprovedResumeContent,
  meta: ImprovedCvMeta
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const regularFont = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const italicFont = await pdfDoc.embedFont(StandardFonts.HelveticaOblique)

  let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  let cursorY = PAGE_HEIGHT - TOP_MARGIN

  const headingColor = rgb(0.77, 0.16, 0.3)
  const bodyColor = rgb(0.15, 0.15, 0.18)
  const mutedColor = rgb(0.36, 0.36, 0.42)
  const sectionColor = rgb(0.55, 0.12, 0.25)

  const title = meta.jobTitle
    ? `Improved CV — ${meta.jobTitle}`
    : "Improved CV"
  page.drawText(title, { x: MARGIN_X, y: cursorY, size: 20, font: boldFont, color: headingColor })
  cursorY -= 18

  if (meta.companyName) {
    page.drawText(`Target company: ${meta.companyName}`, {
      x: MARGIN_X,
      y: cursorY,
      size: 11,
      font: regularFont,
      color: mutedColor,
    })
    cursorY -= 14
  }

  const generatedAt = meta.generatedAt || new Date().toLocaleString()
  page.drawText(`Generated by Resumind — ${generatedAt}`, {
    x: MARGIN_X,
    y: cursorY,
    size: 10,
    font: italicFont,
    color: mutedColor,
  })
  cursorY -= 22

  page.drawRectangle({
    x: MARGIN_X,
    y: cursorY,
    width: CONTENT_WIDTH,
    height: 1,
    color: rgb(0.84, 0.42, 0.56),
  })
  cursorY -= 18

  const sections: Array<{ title: string; body: string }> = [
    { title: "Professional Summary", body: content.summary },
    { title: "Experience", body: content.experience },
    { title: "Skills", body: content.skills },
    { title: "Projects", body: content.projects },
  ]

  for (const section of sections) {
    if (!section.body?.trim()) continue

    const headingEnsure = ensurePage(pdfDoc, page, cursorY, 22)
    page = headingEnsure.page
    cursorY = headingEnsure.cursorY

    page.drawText(section.title, {
      x: MARGIN_X,
      y: cursorY,
      size: 13,
      font: boldFont,
      color: sectionColor,
    })
    cursorY -= 16

    const bodyBlock = drawBlock({
      pdfDoc,
      page,
      cursorY,
      text: section.body,
      font: regularFont,
      size: 10,
      color: bodyColor,
      lineHeight: 14,
    })
    page = bodyBlock.page
    cursorY = bodyBlock.cursorY - 8
  }

  return pdfDoc.save()
}

export function contentToText(content: ImprovedResumeContent): string {
  return [
    content.summary,
    content.experience,
    content.skills,
    content.projects,
  ]
    .filter(Boolean)
    .join("\n\n")
}

export function contentToSections(content: ImprovedResumeContent): Array<{ title: string; body: string }> {
  return [
    { title: "Professional Summary", body: content.summary },
    { title: "Experience", body: content.experience },
    { title: "Skills", body: content.skills },
    { title: "Projects", body: content.projects },
  ]
}
